services:
  astro-template:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-template
    ports:
      - '4321:80'
    environment:
      - BACKEND_URL=http://localhost:3000

  database:
    image: postgres:16
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: